# Default values for dataset-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  requests_cpu: "0.1"
  requests_memory: "256M"
  limits_cpu: "1"
  limits_memory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "dataset-config"
  postgres_secret_name: ""
  app_name: "dataset"
  on_prem_enabled: false
