variables:
  AWS_BUILD_SUBDIR: provider/dataset-aws/build-aws
  AWS_TEST_SUBDIR: testing/dataset-test-aws
  AWS_SERVICE: dataset
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-dataset

  IBM_BUILD_SUBDIR: provider/dataset-ibm
  IBM_INT_TEST_SUBDIR: testing/dataset-test-ibm

  # --- osdu-gcp specific variables ---
  OSDU_GCP_SERVICE: dataset
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: dataset
  OSDU_GCP_FILE_DMS_BUCKET: "file-dms-bucket"
  OSDU_GCP_EXPIRATION_DAYS: 1
  OSDU_GCP_TEST_SUBDIR: testing/$OSDU_GCP_SERVICE-test-$OSDU_GCP_VENDOR
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: "--set data.google_audiences=$GOOGLE_AUDIENCE --set data.redis_group_host=$REDIS_GROUP_HOST --set data.file_dms_bucket=$OSDU_GCP_FILE_DMS_BUCKET --set data.expiration_days=$OSDU_GCP_EXPIRATION_DAYS"
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: "--set data.google_audiences=$GOOGLE_AUDIENCE --set data.redis_group_host=$REDIS_GROUP_HOST --set data.file_dms_bucket=$OSDU_GCP_FILE_DMS_BUCKET --set data.expiration_days=$OSDU_GCP_EXPIRATION_DAYS"
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: "--set data.image=$CI_REGISTRY_IMAGE/osdu-gcp:$CI_COMMIT_SHORT_SHA --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s"
  OSDU_GCP_HELM_CONFIG_SERVICE: dataset-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: dataset-deploy

  #Azure
  AZURE_SERVICE: dataset
  AZURE_BUILD_SUBDIR: provider/dataset-azure
  AZURE_TEST_SUBDIR: testing/dataset-test-azure
  AZURE_COVERAGE_THRESHOLD: $AZURE_CODE_COVERAGE_THRESHOLD

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp-gke.yml"

# disable the eslint scanner
# I think this is being generated from the presence of an HTML file, but there
# is no javascript to scan, so the job isn't helpful and just gets in the way
eslint-sast:
  rules:
    - when: never

osdu-gcp-test:
  variables:
    STORAGE_BASE_URL: $OSDU_GCP_STORAGE_EXTERNAL_URL
    LEGAL_BASE_URL: $OSDU_GCP_LEGAL_EXTERNAL_URL
    DATASET_BASE_URL: $OSDU_GCP_DATASET_EXTERNAL_URL
    SCHEMA_API: $OSDU_GCP_SCHEMA_URL
    PROVIDER_KEY: GCP
    KIND_SUBTYPE: DatasetTest
    LEGAL_TAG: datatest-int-tag
    LEGAL_HOST: $OSDU_GCP_LEGAL_EXTERNAL_URL
    GCP_STORAGE_PERSISTENT_AREA: persistent-area
    GCP_DEPLOY_FILE: $OSDU_GCP_DEPLOY_FILE


osdu-gcp-dev2-test:
  variables:
    STORAGE_BASE_URL: $OSDU_GCP_STORAGE_EXTERNAL_URL
    LEGAL_BASE_URL: $OSDU_GCP_LEGAL_EXTERNAL_URL
    DATASET_BASE_URL: $OSDU_GCP_DATASET_EXTERNAL_URL
    SCHEMA_API: $OSDU_GCP_SCHEMA_URL
    PROVIDER_KEY: GCP
    KIND_SUBTYPE: DatasetTest
    LEGAL_TAG: datatest-int-tag
    LEGAL_HOST: $OSDU_GCP_LEGAL_EXTERNAL_URL
    GCP_STORAGE_PERSISTENT_AREA: persistent-area
    GCP_DEPLOY_FILE: $OSDU_GCP_DEPLOY_FILE
