apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  LOG_LEVEL: "{{ .Values.data.log_level }}"
  FILE_DMS_BUCKET: "{{ .Values.data.file_dms_bucket }}"
  EXPIRATION_DAYS: "{{ .Values.data.expiration_days }}"
  REDIS_GROUP_HOST: "{{ .Values.data.redis_group_host }}"
  REDIS_GROUP_PORT: "{{ .Values.data.redis_group_port }}"
  GOOGLE_AUDIENCES: "{{ .Values.data.google_audiences }}"
